// constants/quiz-data.ts

// Dữ liệu câu hỏi ôn tập cho các ngôn ngữ khác nhau
export const quizData = {
  vi: {
    title: "Ôn tập kiến thức",
    subtitle: "Kiểm tra hiểu biết về tư tưởng Hồ Chí Minh",
    questions: [
      {
        id: 1,
        question: "Theo Hồ Chí Minh, chủ nghĩa xã hội là gì?",
        options: [
          "Xã hội có giai cấp thống trị",
          "Xã hội không có giai cấp bóc lột, mọi người bình đẳng",
          "Xã hội chỉ có một giai cấp duy nhất",
          "Xã hội phân chia theo tài sản",
        ],
        correct: 1,
        explanation:
          "Hồ Chí Minh cho rằng chủ nghĩa xã hội là xã hội không có giai cấp bóc lột, không có áp bức, mọi người đều bình đẳng, tự do và hạnh phúc.",
      },
      {
        id: 2,
        question: "Thời kỳ quá độ lên chủ nghĩa xã hội cần thực hiện điều gì?",
        options: [
          "Chỉ cần phát triển kinh tế",
          "Chỉ cần cải cách chính trị",
          "Cải cách toàn diện về kinh tế, chính trị, văn hóa, xã hội",
          "Chỉ cần giáo dục nhân dân",
        ],
        correct: 2,
        explanation:
          "Thời kỳ quá độ cần chuẩn bị các điều kiện cần thiết về kinh tế, chính trị, văn hóa, xã hội để chuyển sang chủ nghĩa xã hội.",
      },
      {
        id: 3,
        question: "Đặc điểm nào sau đây KHÔNG phải của chủ nghĩa xã hội Việt Nam?",
        options: [
          "Gắn liền với độc lập dân tộc",
          "Áp dụng máy móc mô hình nước ngoài",
          "Lấy nhân dân làm gốc",
          "Kết hợp truyền thống và hiện đại",
        ],
        correct: 1,
        explanation:
          "Chủ nghĩa xã hội Việt Nam không áp dụng máy móc mô hình của nước khác mà phải sáng tạo, phù hợp với điều kiện cụ thể của dân tộc.",
      },
      {
        id: 4,
        question: "Theo V.I. Lênin, ở các nước chưa trải qua giai đoạn phát triển đầy đủ của chủ nghĩa tư bản, cần thực hiện gì để tiến lên chủ nghĩa xã hội?",
        options: [
          "Cách mạng vô sản trực tiếp.",
          "Xây dựng nền kinh tế thị trường tự do.",
          "Thời kỳ quá độ gián tiếp qua công nghiệp hóa, hợp tác hóa.",
          "Loại bỏ hoàn toàn các thành phần kinh tế tư nhân.",
        ],
        correct: 2, // Dựa trên nội dung câu hỏi mới, đáp án là C (index 2)
        explanation: "Ở các nước chậm phát triển, cần thực hiện thời kỳ quá độ gián tiếp, tập trung vào công nghiệp hóa và hợp tác hóa.",
      },
      {
        id: 5,
        question: "Đặc trưng nào sau đây KHÔNG thuộc bản chất của chủ nghĩa xã hội?",
        options: [
          "Do nhân dân lao động làm chủ.",
          "Dựa trên chế độ tư hữu về tư liệu sản xuất.",
          "Giải phóng giai cấp, giải phóng dân tộc.",
          "Có sự lãnh đạo của Đảng Cộng sản.",
        ],
        correct: 1,
        explanation: "Bản chất của chủ nghĩa xã hội là dựa trên chế độ công hữu về tư liệu sản xuất, không phải tư hữu.",
      },
      {
        id: 6,
        question: "Mô hình kinh tế nào được Việt Nam áp dụng để xây dựng chủ nghĩa xã hội?",
        options: [
          "Kinh tế kế hoạch hóa tập trung hoàn toàn.",
          "Kinh tế thị trường định hướng xã hội chủ nghĩa.",
          "Kinh tế tư bản chủ nghĩa tự do.",
          "Kinh tế hỗn hợp không định hướng.",
        ],
        correct: 1,
        explanation: "Việt Nam đang xây dựng chủ nghĩa xã hội dựa trên mô hình kinh tế thị trường định hướng xã hội chủ nghĩa.",
      },
      {
        id: 7,
        question: "Nguyên nhân sâu xa dẫn đến sự ra đời của chủ nghĩa xã hội là gì?",
        options: [
          "Mâu thuẫn giữa các quốc gia trong bối cảnh toàn cầu hóa.",
          "Mâu thuẫn giữa giai cấp công nhân và giai cấp tư sản.",
          "Mâu thuẫn giữa các thành phần kinh tế trong một quốc gia.",
          "Mâu thuẫn giữa các dân tộc trong một quốc gia.",
        ],
        correct: 1,
        explanation: "Sự phát triển của chủ nghĩa tư bản làm nảy sinh mâu thuẫn căn bản giữa giai cấp công nhân và giai cấp tư sản, dẫn đến sự ra đời của chủ nghĩa xã hội.",
      },
      {
        id: 8,
        question: "Sự kiện nào ở Việt Nam tạo tiền đề cho việc xây dựng chủ nghĩa xã hội trên cả nước sau năm 1975?",
        options: [
          "Cách mạng Tháng Tám (1945).",
          "Công cuộc Đổi mới (1986).",
          "Chiến thắng Điện Biên Phủ (1954).",
          "Hiệp định Genève (1954).",
        ],
        correct: 0,
        explanation: "Cách mạng Tháng Tám 1945 đã tạo nền móng cho việc xây dựng chủ nghĩa xã hội ở Việt Nam, và sau năm 1975, đất nước thống nhất đã tiếp tục con đường này.",
      },
      {
        id: 9,
        question: "Vai trò của Đảng Cộng sản trong chủ nghĩa xã hội là gì?",
        options: [
          "Lãnh đạo, tổ chức và định hướng xây dựng xã hội xã hội chủ nghĩa.",
          "Đại diện cho lợi ích của giai cấp tư sản.",
          "Chỉ tham gia vào các hoạt động kinh tế.",
          "Thay thế hoàn toàn vai trò của nhà nước.",
        ],
        correct: 0,
        explanation: "Đảng Cộng sản đóng vai trò hạt nhân lãnh đạo, định hướng sự phát triển của xã hội xã hội chủ nghĩa.",
      },
      {
        id: 10,
        question: "Đặc trưng “phát triển văn hóa, giáo dục, khoa học và công bằng xã hội” ở Việt Nam được thể hiện qua việc nào?",
        options: [
          "Xây dựng nhà nước pháp quyền xã hội chủ nghĩa.",
          "Tăng cường hợp tác quốc tế với ASEAN.",
          "Thúc đẩy phổ cập giáo dục và xóa đói giảm nghèo.",
          "Xây dựng nền kinh tế thị trường tự do.",
        ],
        correct: 2,
        explanation: "Việc thúc đẩy phổ cập giáo dục và xóa đói giảm nghèo là những biểu hiện cụ thể của việc phát triển văn hóa, giáo dục và công bằng xã hội.",
      },
      {
        id: 11,
        question: "Chế độ công hữu về tư liệu sản xuất trong chủ nghĩa xã hội bao gồm những hình thức nào?",
        options: [
          "Sở hữu tư nhân và sở hữu hỗn hợp.",
          "Sở hữu cá nhân và sở hữu tập thể.",
          "Sở hữu nhà nước và sở hữu tập thể.",
          "Sở hữu nhà nước và sở hữu tư nhân.",
        ],
        correct: 2,
        explanation: "Chế độ công hữu bao gồm sở hữu nhà nước (đại diện cho toàn dân) và sở hữu tập thể (của các tổ chức, hợp tác xã).",
      },
      {
        id: 12,
        question: "Theo C. Mác, chủ nghĩa xã hội là sự phủ định biện chứng đối với chế độ nào?",
        options: [
          "Chế độ tư bản chủ nghĩa.",
          "Chế độ phong kiến.",
          "Chế độ quân chủ.",
          "Chế độ nô lệ.",
        ],
        correct: 0,
        explanation: "Chủ nghĩa xã hội ra đời là sự kế thừa những thành tựu của nhân loại và phủ định những mặt tiêu cực của chủ nghĩa tư bản.",
      },
      {
        id: 13,
        question: "Mục tiêu cốt lõi của chủ nghĩa xã hội là gì?",
        options: [
          "Tăng cường quyền lực của giai cấp tư sản.",
          "Xây dựng một xã hội không có nhà nước ngay từ đầu.",
          "Giải phóng con người khỏi áp bức, bóc lột, hướng tới bình đẳng.",
          "Phát triển kinh tế tư bản chủ nghĩa.",
        ],
        correct: 2,
        explanation: "Mục tiêu cao nhất của chủ nghĩa xã hội là giải phóng con người, xây dựng một xã hội công bằng, dân chủ, văn minh.",
      },
      {
        id: 14,
        question: "Sự kiện lịch sử nào được coi là minh chứng đầu tiên cho khả năng xây dựng chủ nghĩa xã hội ở các nước lạc hậu?",
        options: [
          "Cách mạng Pháp (1789).",
          "Cách mạng Tháng Mười Nga (1917).",
          "Cách mạng Mỹ (1776).",
          "Cách mạng Tháng Tám Việt Nam (1945).",
        ],
        correct: 1,
        explanation: "Cách mạng Tháng Mười Nga đã mở ra kỷ nguyên độc lập dân tộc gắn liền với chủ nghĩa xã hội, chứng minh rằng chủ nghĩa xã hội có thể thắng lợi ở các nước kém phát triển.",
      },
      {
        id: 15,
        question: "Đặc trưng “đoàn kết dân tộc và đoàn kết quốc tế” của chủ nghĩa xã hội ở Việt Nam được thể hiện qua việc nào?",
        options: [
          "Xây dựng nhà nước pháp quyền xã hội chủ nghĩa.",
          "Tham gia các tổ chức quốc tế như Liên Hợp Quốc, ASEAN.",
          "Phát triển kinh tế thị trường tự do.",
          "Thúc đẩy phổ cập giáo dục.",
        ],
        correct: 1,
        explanation: "Việc tham gia tích cực vào các tổ chức quốc tế thể hiện tinh thần đoàn kết quốc tế của Việt Nam.",
      },
      {
        id: 16,
        question: "Theo chủ nghĩa Mác - Lênin, nhà nước trong chủ nghĩa xã hội có đặc điểm gì?",
        options: [
          "Là công cụ của giai cấp tư sản.",
          "Là nhà nước của dân, do dân, vì dân.",
          "Không tồn tại trong xã hội xã hội chủ nghĩa.",
          "Chỉ phục vụ lợi ích của tầng lớp trung lưu.",
        ],
        correct: 1,
        explanation: "Nhà nước xã hội chủ nghĩa mang bản chất của giai cấp công nhân, là công cụ để nhân dân lao động thực hiện quyền làm chủ của mình.",
      },
      {
        id: 17,
        question: "Công cuộc Đổi mới ở Việt Nam (từ năm 1986) nhằm mục tiêu gì?",
        options: [
          "Xây dựng nền kinh tế thị trường tự do hoàn toàn.",
          "Cụ thể hóa mô hình kinh tế thị trường định hướng xã hội chủ nghĩa.",
          "Loại bỏ hoàn toàn các thành phần kinh tế tư nhân.",
          "Xây dựng chế độ phong kiến hiện đại.",
        ],
        correct: 1,
        explanation: "Đổi mới nhằm xây dựng và phát triển nền kinh tế thị trường định hướng xã hội chủ nghĩa, phù hợp với điều kiện Việt Nam.",
      },
      {
        id: 18,
        question: "Theo V.I. Lênin, chủ nghĩa xã hội là sản phẩm của gì?",
        options: [
          "Cách mạng tư sản.",
          "Cách mạng vô sản.",
          "Sự phát triển tự nhiên của kinh tế thị trường.",
          "Sự hợp tác giữa các giai cấp trong xã hội.",
        ],
        correct: 1,
        explanation: "Lênin khẳng định chủ nghĩa xã hội là kết quả trực tiếp của cách mạng vô sản.",
      },
      {
        id: 19,
        question: "Đặc trưng nào của chủ nghĩa xã hội nhấn mạnh sự phát triển toàn diện con người?",
        options: [
          "Giải phóng giai cấp, giải phóng dân tộc, giải phóng xã hội.",
          "Có sự lãnh đạo của Đảng Cộng sản.",
          "Dựa trên chế độ công hữu về tư liệu sản xuất.",
          "Đoàn kết dân tộc và đoàn kết quốc tế.",
        ],
        correct: 0,
        explanation: "Sự giải phóng con người một cách toàn diện bao gồm cả giải phóng giai cấp, dân tộc và khỏi mọi hình thức áp bức, bóc lột.",
      },
      {
        id: 20,
        question: "Ở Việt Nam, quyền làm chủ của nhân dân lao động được thực hiện thông qua cơ chế nào?",
        options: [
          "Quốc hội, Mặt trận Tổ quốc và các tổ chức chính trị - xã hội.",
          "Các tổ chức kinh tế tư nhân.",
          "Các tổ chức quốc tế như Liên Hợp Quốc.",
          "Các cơ quan hành chính địa phương độc lập.",
        ],
        correct: 0,
        explanation: "Hệ thống chính trị Việt Nam, bao gồm Quốc hội, Mặt trận Tổ quốc và các tổ chức thành viên, là cơ chế để nhân dân thực hiện quyền làm chủ.",
      },
    ],
  },
  en: {
    title: "Knowledge Review",
    subtitle: "Test your understanding of Ho Chi Minh's thought",
    questions: [
      {
        id: 1,
        question: "According to Marx-Leninism, what is socialism?",
        options: [
          "A perfect society with no classes from the start.",
          "A society based on private ownership of the means of production.",
          "The initial stage of the communist mode of production.",
          "The final stage of capitalism.",
        ],
        correct: 2,
        explanation:
          "Socialism is considered the first phase of communist society, characterized by the transition from capitalism.",
      },
      {
        id: 2,
        question: "According to K. Marx in 'Critique of the Gotha Program', what is the principle of distribution in socialism?",
        options: [
          "From each according to his ability, to each according to his need.",
          "From each according to his need, to each according to his ability.",
          "From each according to his ability, to each equally.",
          "From each according to his ability, to each according to his labor.",
        ],
        correct: 3,
        explanation: "In the socialist stage, distribution is based on the principle of 'from each according to his ability, to each according to his labor.'",
      },
      {
        id: 3,
        question: "What is the material prerequisite for the emergence of socialism?",
        options: [
          "The leadership of the Communist Party.",
          " The highly developed productive forces under capitalism.",
          "The solidarity of ethnic groups within a nation.",
          "The maturity of the bourgeoisie.",
        ],
        correct: 1,
        explanation: "The development of advanced productive forces under capitalism creates the material conditions for socialism.",
      },
      {
        id: 4,
        question: "According to V.I. Lenin, in countries that have not gone through the full stage of capitalism, what needs to be done to advance towards socialism?",
        options: [
          "Direct proletarian revolution.",
          "Building a free market economy.",
          "An indirect transition period through industrialization and collectivization.",
          "Completely eliminating private economic sectors.",
        ],
        correct: 2,
        explanation: "In less developed countries, an indirect transition period focusing on industrialization and collectivization is necessary.",
      },
      {
        id: 5,
        question: "Which characteristic does NOT belong to the essence of socialism?",
        options: [
          "Owned and controlled by the working people.",
          "Based on private ownership of the means of production.",
          "Liberation of classes and nations.",
          "Led by the Communist Party.",
        ],
        correct: 1,
        explanation: "The essence of socialism is based on public ownership of the means of production, not private ownership.",
      },
      {
        id: 6,
        question: "What economic model does Vietnam adopt to build socialism?",
        options: [
          "A completely centrally planned economy.",
          "A socialist-oriented market economy.",
          "A free capitalist economy.",
          "An undirected mixed economy.",
        ],
        correct: 1,
        explanation: "Vietnam is building socialism based on a socialist-oriented market economy model.",
      },
      {
        id: 7,
        question: "What is the root cause of the emergence of socialism?",
        options: [
          "Contradictions between nations in the context of globalization.",
          "The contradiction between the working class and the bourgeoisie.",
          "Contradictions between economic sectors within a nation.",
          "Contradictions between ethnic groups within a nation.",
        ],
        correct: 1,
        explanation: "The development of capitalism creates the fundamental contradiction between the working class and the bourgeoisie, leading to the emergence of socialism.",
      },
      {
        id: 8,
        question: "Which event in Vietnam laid the foundation for building socialism nationwide after 1975?",
        options: [
          "The August Revolution (1945).",
          "The Renovation (Đổi Mới) process (1986).",
          "The Điện Biên Phủ Victory (1954).",
          "The Geneva Accords (1954).",
        ],
        correct: 0,
        explanation: "The August Revolution of 1945 laid the groundwork for building socialism in Vietnam, and after 1975, the unified country continued on this path.",
      },
      {
        id: 9,
        question: "What is the role of the Communist Party in socialism?",
        options: [
          "To lead, organize, and guide the building of a socialist society.",
          "To represent the interests of the bourgeoisie.",
          "To only participate in economic activities.",
          "To completely replace the role of the state.",
        ],
        correct: 0,
        explanation: "The Communist Party plays the core leadership role, guiding the development of socialist society.",
      },
      {
        id: 10,
        question: "The characteristic of 'developing culture, education, science, and social justice' in Vietnam is manifested through which actions?",
        options: [
          "Building a socialist rule of law state.",
          "Strengthening international cooperation with ASEAN.",
          "Promoting universal education and poverty reduction.",
          "Building a free market economy.",
        ],
        correct: 2,
        explanation: "Promoting universal education and poverty reduction are concrete manifestations of developing culture, education, and social justice.",
      },
      {
        id: 11,
        question: "What forms does public ownership of the means of production in socialism include?",
        options: [
          "Private ownership and mixed ownership.",
          "Personal ownership and collective ownership.",
          "State ownership and collective ownership.",
          "State ownership and private ownership.",
        ],
        correct: 2,
        explanation: "Public ownership includes state ownership (representing the entire nation) and collective ownership (of organizations, cooperatives).",
      },
      {
        id: 12,
        question: "According to K. Marx, socialism is the dialectical negation of which system?",
        options: [
          "The capitalist system.",
          "The feudal system.",
          "The monarchical system.",
          "The slave system.",
        ],
        correct: 0,
        explanation: "Socialism arises as a succession to humanity's achievements and a negation of the negative aspects of capitalism.",
      },
      {
        id: 13,
        question: "What is the core goal of socialism?",
        options: [
          "To strengthen the power of the bourgeoisie.",
          "To build a stateless society from the outset.",
          "To liberate humanity from oppression and exploitation, moving towards equality.",
          "To develop the capitalist economy.",
        ],
        correct: 2,
        explanation: "The ultimate goal of socialism is the liberation of humanity and the construction of a just, democratic, and civilized society.",
      },
      {
        id: 14,
        question: "Which historical event is considered the first evidence of the possibility of building socialism in less developed countries?",
        options: [
          "The French Revolution (1789).",
          "The October Revolution in Russia (1917).",
          "The American Revolution (1776).",
          "The August Revolution in Vietnam (1945).",
        ],
        correct: 1,
        explanation: "The October Revolution in Russia ushered in an era of national independence linked with socialism, demonstrating that socialism could triumph in less developed countries.",
      },
      {
        id: 15,
        question: "The characteristic of 'national solidarity and international solidarity' of socialism in Vietnam is manifested through which actions?",
        options: [
          "Building a socialist rule of law state.",
          "Participating in international organizations such as the United Nations, ASEAN.",
          "Developing a free market economy.",
          "Promoting universal education.",
        ],
        correct: 1,
        explanation: "Active participation in international organizations demonstrates Vietnam's spirit of international solidarity.",
      },
      {
        id: 16,
        question: "According to Marx-Leninism, what are the characteristics of the state in socialism?",
        options: [
          "It is an instrument of the bourgeoisie.",
          "It is a state of the people, by the people, for the people.",
          "It does not exist in a socialist society.",
          "It only serves the interests of the middle class.",
        ],
        correct: 1,
        explanation: "The socialist state embodies the nature of the working class and serves as a tool for the working people to exercise their right to self-governance.",
      },
      {
        id: 17,
        question: "What is the objective of the Renovation (Đổi Mới) process in Vietnam (since 1986)?",
        options: [
          "To build a completely free market economy.",
          "To specify the socialist-oriented market economy model.",
          "To completely eliminate private economic sectors.",
          "To build a modern feudal system.",
        ],
        correct: 1,
        explanation: "The Renovation aims to build and develop a socialist-oriented market economy, suitable for Vietnam's conditions.",
      },
      {
        id: 18,
        question: "According to V.I. Lenin, socialism is a product of what?",
        options: [
          "Bourgeois revolution.",
          "Proletarian revolution.",
          "Natural development of the market economy.",
          "Cooperation between social classes.",
        ],
        correct: 1,
        explanation: "Lenin affirmed that socialism is the direct result of the proletarian revolution.",
      },
      {
        id: 19,
        question: "Which characteristic of socialism emphasizes the comprehensive development of the individual?",
        options: [
          "Liberation of classes, nations, and society.",
          "Led by the Communist Party.",
          "Based on public ownership of the means of production.",
          "National and international solidarity.",
        ],
        correct: 0,
        explanation: "The comprehensive liberation of humanity includes the liberation of classes, nations, and from all forms of oppression and exploitation.",
      },
      {
        id: 20,
        question: "In Vietnam, through which mechanism is the right of the working people to be masters exercised?",
        options: [
          "The National Assembly, the Fatherland Front, and political-social organizations.",
          "Private economic organizations.",
          "International organizations such as the United Nations.",
          "Independent local administrative bodies.",
        ],
        correct: 0,
        explanation: "Vietnam's political system, including the National Assembly, the Fatherland Front, and its member organizations, serves as the mechanism for the people to exercise their right to self-governance.",
      },
    ],
  },
  ja: {
    title: "知識の復習",
    subtitle: "ホー・チ・ミンの思想の理解度をテスト",
    questions: [
      {
        id: 1,
        question: "マルクス・レーニン主義によれば、社会主義とは何ですか？",
        options: [
          "最初から階級のない完璧な社会。",
          "生産手段の私的所有に基づく社会。",
          "共産主義社会形態の初期段階。",
          "資本主義の最終段階。",
        ],
        correct: 2,
        explanation: "社会主義は、資本主義からの移行を特徴とする共産主義社会の最初の段階と見なされます。",
      },
      {
        id: 2,
        question: "K.マルクスは『ゴータ綱領批判』で、社会主義における分配原則は何であると述べていますか？",
        options: [
          "能力に応じて働き、必要に応じて受け取る。",
          "必要に応じて働き、能力に応じて受け取る。",
          "能力に応じて働き、均等に受け取る。",
          "能力に応じて働き、労働に応じて受け取る。",
        ],
        correct: 3,
        explanation: "社会主義段階では、分配は「能力に応じて働き、労働に応じて受け取る」という原則に基づいています。",
      },
      {
        id: 3,
        question: "社会主義の出現のための物質的基盤は何ですか？",
        options: [
          "共産党の指導。",
          "資本主義下で高度に発達した生産力。",
          "一国内の諸民族の団結。",
          "ブルジョワジーの成熟。",
        ],
        correct: 1,
        explanation: "資本主義下での高度な生産力の発展が、社会主義の物質的条件を創り出します。",
      },
      {
        id: 4,
        question: "V.I.レーニンによれば、資本主義の発展段階を十分に経ていない国々では、社会主義へ進むために何をする必要がありますか？",
        options: [
          "直接的なプロレタリア革命。",
          "自由市場経済の構築。",
          "工業化と協同組合化を通じた間接的な移行期間。",
          "私的経済部門の完全な廃止。",
        ],
        correct: 2,
        explanation: "発展の遅れた国々では、工業化と協同組合化に焦点を当てた間接的な移行期間が必要です。",
      },
      {
        id: 5,
        question: "社会主義の本質に属さない特徴はどれですか？",
        options: [
          "労働者階級によって所有・管理される。",
          "生産手段の私的所有に基づく。",
          "階級と民族の解放。",
          "共産党の指導。",
        ],
        correct: 1,
        explanation: "社会主義の本質は生産手段の公的所有に基づくものであり、私的所有ではありません。",
      },
      {
        id: 6,
        question: "ベトナムは社会主義建設のためにどのような経済モデルを採用していますか？",
        options: [
          "完全に中央計画経済。",
          "社会主義志向の市場経済。",
          "自由な資本主義経済。",
          "方向性のない混合経済。",
        ],
        correct: 1,
        explanation: "ベトナムは、社会主義志向の市場経済モデルに基づいて社会主義を建設しています。",
      },
      {
        id: 7,
        question: "社会主義出現の根本原因は何ですか？",
        options: [
          "グローバル化の文脈における国家間の矛盾。",
          "労働者階級とブルジョワジーの間の矛盾。",
          "一国内の経済部門間の矛盾。",
          "一国内の民族間の矛盾。",
        ],
        correct: 1,
        explanation: "資本主義の発展は、労働者階級とブルジョワジーの間の根本的な矛盾を生み出し、社会主義の出現につながります。",
      },
      {
        id: 8,
        question: "1975年以降、ベトナム全土での社会主義建設の基礎を築いた出来事は何ですか？",
        options: [
          "8月革命（1945年）。",
          "刷新（Đổi Mới）プロセス（1986年）。",
          "ディエンビエンフーの戦い（1954年）。",
          "ジュネーブ協定（1954年）。",
        ],
        correct: 0,
        explanation: "1945年の8月革命は、ベトナムにおける社会主義建設の基盤を築き、1975年以降、統一された国家はこの道を継続しました。",
      },
      {
        id: 9,
        question: "社会主義における共産党の役割は何ですか？",
        options: [
          "社会主義社会の建設を指導、組織、指導する。",
          "ブルジョワジーの利益を代表する。",
          "経済活動のみに参加する。",
          "国家の役割を完全に置き換える。",
        ],
        correct: 0,
        explanation: "共産党は、社会主義社会の発展を指導する中心的な役割を果たします。",
      },
      {
        id: 10,
        question: "ベトナムにおける「文化、教育、科学、社会正義の発展」という特徴は、どのような行動によって表されますか？",
        options: [
          "社会主義法治国家の建設。",
          "ASEANとの国際協力の強化。",
          "普遍的な教育と貧困削減の促進。",
          "自由市場経済の構築。",
        ],
        correct: 2,
        explanation: "普遍的な教育の促進と貧困削減は、文化、教育、社会正義の発展の具体的な現れです。",
      },
      {
        id: 11,
        question: "社会主義における生産手段の公的所有にはどのような形態が含まれますか？",
        options: [
          "私的所有と混合所有。",
          "個人所有と集団所有。",
          "国家所有と集団所有。",
          "国家所有と私的所有。",
        ],
        correct: 2,
        explanation: "公的所有には、国家所有（国民全体を代表する）と集団所有（組織、協同組合の）が含まれます。",
      },
      {
        id: 12,
        question: "K.マルクスによれば、社会主義はどのような体制の弁証法的否定ですか？",
        options: [
          "資本主義体制。",
          "封建制度。",
          "君主制。",
          "奴隷制度。",
        ],
        correct: 0,
        explanation: "社会主義は、人類の成果を継承し、資本主義の否定的な側面を否定するものとして登場します。",
      },
      {
        id: 13,
        question: "社会主義の核心的な目標は何ですか？",
        options: [
          "ブルジョワジーの権力を強化する。",
          "当初から国家のない社会を建設する。",
          "人間を抑圧と搾取から解放し、平等をめざす。",
          "資本主義経済を発展させる。",
        ],
        correct: 2,
        explanation: "社会主義の究極の目標は、人間の解放と、公正で民主的で文明的な社会の建設です。",
      },
      {
        id: 14,
        question: "後発国における社会主義建設の可能性を最初に証明した歴史的出来事は何と見なされますか？",
        options: [
          "フランス革命（1789年）。",
          "ロシア十月革命（1917年）。",
          "アメリカ独立革命（1776年）。",
          "ベトナム8月革命（1945年）。",
        ],
        correct: 1,
        explanation: "ロシア十月革命は、民族独立と社会主義を結びつける時代の幕開けとなり、後発国でも社会主義が勝利する可能性を証明しました。",
      },
      {
        id: 15,
        question: "ベトナムにおける社会主義の「民族連帯と国際連帯」という特徴は、どのような行動によって表されますか？",
        options: [
          "社会主義法治国家の建設。",
          "国連、ASEANなどの国際組織への参加。",
          "自由市場経済の発展。",
          "普遍的な教育の促進。",
        ],
        correct: 1,
        explanation: "国際組織への積極的な参加は、ベトナムの国際連帯の精神を示しています。",
      },
      {
        id: 16,
        question: "マルクス・レーニン主義によれば、社会主義における国家はどのような特徴を持っていますか？",
        options: [
          "ブルジョワジーの道具である。",
          "人民の、人民による、人民のための国家である。",
          "社会主義社会には存在しない。",
          "中間層の利益のみを奉仕する。",
        ],
        correct: 1,
        explanation: "社会主義国家は、労働者階級の本質を体現し、労働人民が自己統治権を行使するための道具となります。",
      },
      {
        id: 17,
        question: "ベトナムにおける刷新（Đổi Mới）プロセス（1986年以降）の目的は何ですか？",
        options: [
          "完全に自由な市場経済を構築する。",
          "社会主義志向の市場経済モデルを具体化する。",
          "私的経済部門を完全に廃止する。",
          "現代の封建制度を構築する。",
        ],
        correct: 1,
        explanation: "刷新は、ベトナムの状況に適した社会主義志向の市場経済を構築・発展させることを目指しています。",
      },
      {
        id: 18,
        question: "V.I.レーニンによれば、社会主義は何の産物ですか？",
        options: [
          "ブルジョワ革命。",
          "プロレタリア革命。",
          "市場経済の自然な発展。",
          "社会階級間の協力。",
        ],
        correct: 1,
        explanation: "レーニンは、社会主義がプロレタリア革命の直接の結果であると断言しました。",
      },
      {
        id: 19,
        question: "社会主義のどの特徴が、人間の包括的な発展を強調していますか？",
        options: [
          "階級、民族、社会の解放。",
          "共産党の指導。",
          "生産手段の公的所有に基づく。",
          "民族および国際連帯。",
        ],
        correct: 0,
        explanation: "人間全体の包括的な解放には、階級、民族、そしてあらゆる形態の抑圧と搾取からの解放が含まれます。",
      },
      {
        id: 20,
        question: "ベトナムでは、労働人民の主人としての権利はどのようなメカニズムを通じて行使されますか？",
        options: [
          "国民議会、祖国戦線、および政治・社会組織。",
          "民間の経済組織。",
          "国連などの国際組織。",
          "独立した地方行政機関。",
        ],
        correct: 0,
        explanation: "ベトナムの政治システム、国民議会、祖国戦線、およびその構成組織は、人民が自己統治権を行使するためのメカニズムとして機能します。",
      },
    ],
  },
}